### PR TITLE
TECC RSNT doc

### PR DESCRIPTION
**Pull request by ofisette**
This pulls in the RSNT documentation from the TECC wiki. I converted https://wiki.computecanada.ca/staff/Software_installation and pages linked therein during this week and the last. I reviewed all changes on the wiki today to make sure this is up-to-date. All converted pages have been reviewed for correctness and all links were tested. Links that point to pages restricted to CC staff have been marked as “CC staff link”.

This change is broken over several commits. The first one is the MediaWiki to MarkDown conversion itself, with no content change except the occasional typo or minor change to better fit the MD format. The other commits are small fixes that improve the docs, avoid exposing a staff email, and link the docs to the README.

### CODE REVIEW

**Comment by lemairecarl** [comment]
Nice! Looks good to me.

Have you considered using GitHub's wiki functionality? It works with markdown, and can be edited locally as a git repo: https://docs.github.com/en/github/building-a-strong-community/adding-or-editing-wiki-pages#adding-or-editing-wiki-pages-locally

**Comment by ofisette** [comment]
Following suggestions, I removed several sections that should remain on the staff wiki; I squashed all commits to prevent these from showing up in the history. Notably, the index is much more concise, with only a summary of the purpose and tools used for the software stack. The setup page now concerns itself only with setting up the Git repos, nothing about how to enable staff access. I purged most staff-only links.

I have not made any change to the wiki yet, as I would prefer to first agree on what should be on GitHub and how it should be structured. We can change the wiki in a second step.

**Comment by ofisette** [comment]
> Nice! Looks good to me.
> 
> Have you considered using GitHub's wiki functionality? It works with markdown, and can be edited locally as a git repo: https://docs.github.com/en/github/building-a-strong-community/adding-or-editing-wiki-pages#adding-or-editing-wiki-pages-locally

A wiki might be nice, but I am not sure what additional functionality it would bring us; this would need to be investigated first. I did not even know GitHub had that feature. I would keep this as a separate issue, though, and first try to get the content moved.

**Comment by ostueker** [comment]
I don't think it makes any difference. We can even edit the .md pages via the Web-UI in the main repo.

In projects with actual code you can use the wiki to keep certain documentation separated from the code and allow everyone to contribute to the wiki while keeping access to the code more strict (PR, etc).  But as this is a meta-repo anyway, I don't see a benefit from using a wiki.

> A Wiki is where information goes to die.
:-D

**Comment by mboisson** [comment]
@ofisette, can you redirect the internal pages to this new documentation ?

**Pull request merged**
